(global-auto-revert-mode +1)

(global-gumshoe-mode +1)
(window-divider-mode +1)
(minibuffer-depth-indicate-mode +1)
(savehist-mode +1)
(winner-mode +1)
(vertico-mode +1)
(vertico-mouse-mode +1)
(vertico-multiform-mode +1)
(marginalia-mode +1)
(global-anzu-mode +1)
(doom-modeline-mode 1)
(global-diff-hl-mode +1)
(global-vi-tilde-fringe-mode +1)
(persp-mode +1)
(diredfl-global-mode)
(highlight-defined-mode +1)
(global-hl-line-mode +1)
(minions-mode)
(which-key-mode)

(load-theme 'dracula t)
(good-scroll-mode +1)
(global-corfu-mode +1)
(recentf-mode +1)
(yas-global-mode +1)

(provide '+modes)
